//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace front_end_demo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class demo_front_end_V2Entities1 : DbContext
    {
        public demo_front_end_V2Entities1()
            : base("name=demo_front_end_V2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<metaFactTest1> metaFactTest1 { get; set; }
        public virtual DbSet<userInfo> userInfoes { get; set; }
        public virtual DbSet<total> totals { get; set; }
    }
}
