//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace front_end_demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class metaFactTest1
    {
        public int UID { get; set; }
        public string id { get; set; }
        public string filter { get; set; }
        public string fileName { get; set; }
        public string fileRoot { get; set; }
        public string RootReference { get; set; }
        public string securityClass { get; set; }
        public string businessClass { get; set; }
        public string filePath { get; set; }
        public string extension { get; set; }
        public string mimeType { get; set; }
        public string MD5 { get; set; }
        public string emailID { get; set; }
        public string emailNew { get; set; }
    }
}
