//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace front_end_demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class total
    {
        public long UID { get; set; }
        public string totalFiles { get; set; }
        public string totalRemediated { get; set; }
        public string percentRemedited { get; set; }
        public string PII { get; set; }
        public string PCI { get; set; }
        public string RET { get; set; }
        public string SPEC { get; set; }
        public string Public { get; set; }
        public string Internal { get; set; }
        public string Classified { get; set; }
        public string ClassifiedSen { get; set; }
        public string Secret { get; set; }
    }
}
